import os
from datetime import datetime

def save_report(topic, analysis, queries, num_sources):
    """Save research results as a markdown file."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"outputs/research_{timestamp}.md"
    
    report = f"""# Research Report
**Topic:** {topic}
**Date:** {datetime.now().strftime("%B %d, %Y %H:%M")}
**Sources Searched:** {num_sources}

## Search Queries Used
{chr(10).join(f"- {q}" for q in queries)}

## Analysis
{analysis}

---
*Generated by AI Research Agent*
"""
    
    # Make sure outputs folder exists
    os.makedirs("outputs", exist_ok=True)
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    
    return filename